FROM python:3.6


RUN pip3 install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r  requirements.txt

WORKDIR /work

COPY ./train_hp.py /work/train_hp.py

ENTRYPOINT ["python",  "train_hp.py"]
